Traceback (most recent call last):
  File "/Users/fynnfu/PycharmProjects/TelegramBots/ZangerKZ/views.py", line 307, in generate_gpt_response
    completion = client.chat.completions.create(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 594, in create
    return self._post(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 834, in request
    return self._request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 865, in _request
    return self._retry_request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 865, in _request
    return self._retry_request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/openai/_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
