Traceback (most recent call last):
  File "/Users/fynnfu/PycharmProjects/TelegramBots/ChatGPT/views.py", line 129, in wrapper
    model=GPTModels.objects.get(name="GPT-4")
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/fynnfu/PycharmProjects/TelegramBots/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ChatGPT.models.GPTModels.DoesNotExist: GPTModels matching query does not exist.
